---
kubernetes_version: v1.26.7
capi_image_name: ubuntu-2204-kube-v1.26.7

capi_provider_version: v0.8.0

cluster_name: capi-cluster
cluster_namespace: default

default_security_group_id: e73a47e9-cc3a-4986-95f9-c3d101c3d448

network_id: 
router_id: 

openstack_ssh_key: kahus-key

cluster_control_plane_count: 1
control_plane_flavor: balanced1.2cpu4ram

cluster_worker_count: 2
worker_flavour: balanced1.2cpu4ram

cluster_node_cidr: 10.10.0.0/24

cluster_pod_cidr: 192.168.0.0/16

bin_dir: /usr/local/bin

clouds_yaml_local_location: ~/.config/openstack/clouds.yaml
clouds_yaml_location: /tmp/clouds.yaml

yq_version: v4.2.0 
yq_repo: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"