---
- name: Check kind cluster is setup
  shell: >-
    kind get clusters
  become: true
  register: kind_cluster_status

- name: debug output
  debug:
    var: kind_cluster_status.stdout_lines

- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yaml.j2"
    dest: "/tmp/cluster-config.yaml"
    mode: 0644
  when: not (kind_cluster_status.stdout_lines | length > 0)

- name: Create kind cluster
  shell: >-
    kind create cluster --name {{ cluster_name }} --config /tmp/cluster-config.yaml
  become: true
  when: not (kind_cluster_status.stdout_lines | length > 0)

- name: Cluster creation has been finished
  debug:
    msg: "Cluster creation of kind cluster {{ cluster_name }} has been finished."
  when: not (kind_cluster_status.stdout_lines | length > 0)
