---
- name: Download kind to specified location {{ bin_dir }}
  get_url:
    url: "{{ kind_repo }}"
    dest: "{{ bin_dir }}/kind"
    mode: 0755
    force: true
  become: true

- name: Installation has been finished
  debug:
    msg: "Installation of kind version {{ kind_version }} has been finished!"
